### PR TITLE
Sort My Comparisons according to last updated comparisons

### PR DESCRIPTION
**Pull request by sandre35**
Related issue : https://github.com/tournesol-app/tournesol-meta/issues/107
I add a migration of db to make the argument `datetime_lastedit` update automatically.

### CODE REVIEW

**Comment by GresilleSiffle** [comment]
Hello @sandre35 

I saw there was already an ordering feature in DRF:
- default ordering: https://www.django-rest-framework.org/api-guide/filtering/#specifying-a-default-ordering
- ordering by a query parameter: https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter

Do you think it's good idea to set the `ordering` attribute of our view?

**Comment by sandre35** [comment]
Hi @GresilleSiffle,
In your first link, the major advantage concerns redering template. As we are using React in our front application, we do not get a lot from this. I find it better to write next to queryset. So we know for sure what is going on instead of hiding it somewhere in another part of the code.
Concerning your second link, I think this may be useful. It depends if we want to do that ordering each time we call `ComparisonListView`. Maybye @lfaucon can this last question

**Comment by GresilleSiffle** [comment]
> In your first link, the major advantage concerns redering template. As we are using React in our front application, we do not get a lot from this. I find it better to write next to queryset. So we know for sure what is going on instead of hiding it somewhere in another part of the code.

That's true, both approaches seems to be very similar for an API.

I'll take the time to review the tests tonight if no one does it before, but currently they look good : )

**Review by lfaucon — APPROVED** [review]
LGTM! If the need arises later we can choose one of Oizo's proposition. For now this suits our need well

**Review by GresilleSiffle — APPROVED** [review]

**Pull request merged**
